### PR TITLE
add rangeCounter that count the num of interval between the two dates

### PR DESCRIPTION
**Pull request by antoinebou12**
image

locale.rangeCounter: ["days", "month", "year"]

### CODE REVIEW

**Comment by dangrossman** [comment]
Nobody else has asked for this feature, so I do not want to maintain it for your project

**Comment by debo900** [comment]
Find the code in js file -
`this.container.find('.drp-selected').html(this.startDate.format(this.locale.format) + this.locale.separator + this.endDate.format(this.locale.format));`

Now add this code
`this.container.find('.count-days').html((this.endDate.diff(this.startDate, 'days')+1).toString()+" days");`

Don't forget to add something like this where you want to show the count
`<span class="count-days">Please Select Date</span>`

aadaa

**Comment by antoinebou12** [comment]
I don't really need this feature anymore, because I work at companies that needed this feature for scheduling vacation.I still think it's a cool feature to have because I didn't see a lot of simple js date picker with count the num of interval between the two dates.


> Find the code in js file -
> `this.container.find('.drp-selected').html(this.startDate.format(this.locale.format) + this.locale.separator + this.endDate.format(this.locale.format));`
> 
> Now add this code
> `this.container.find('.count-days').html((this.endDate.diff(this.startDate, 'days')+1).toString()+" days");`
> 
> Don't forget to add something like this where you want to show the count
> `<span class="count-days">Please Select Date</span>`
> 
> aadaa

If you want to do a pull request on my fork I don't mind

**Comment by antoinebou12** [comment]
@debapriya1990 I fix it, but I don't think I going to work on this issue again. If you want you can change my code with your improvement
https://github.com/antoinebou13/daterangepicker

**Pull request closed without merging**
