### PR TITLE
fix removal of cutom range button if alwaysShowCalendars

### PR DESCRIPTION
**Pull request by RobertSchouten**

### CODE REVIEW

**Comment by dangrossman** [comment]
The list of ranges serves three purposes: allowing the selection of a predefined range, displaying the calendars to choose a custom range, and showing whether the current selection corresponds to one of the ranges in the list or is a custom selection. This last purpose is served by the inclusion of "Custom Range" in the list even when "alwaysShowCalendars" is enabled.

**Comment by k-funk** [comment]
I also find this awkward. If alwaysShowCalendars is true, and I click Custom Range, nothing happens. This "button" isn't actually a button, it's an item on a list that reflects the context of the calendar choices, while the other ranges are buttons that actually perform a function. Dead buttons are bad for UX.

I think it'd be best to hide Custom Ranges until the user actually chooses a custom range on the calendars, or always hide it.

**Comment by dangrossman** [comment]
The option `showCustomRangeLabel` was added 10 months ago

**Comment by k-funk** [comment]
Missed that. Thank you!

**Pull request closed without merging**
