### PR TITLE
Added option 'template'

### PR DESCRIPTION
**Pull request by savaa**
Added option 'template' for overriding default template

### CODE REVIEW

**Comment by gmatroskin** [comment]
@dangrossman any update on possibility of merging this PR?  As mentioned above, having an option like `template` would save many of us from having to either fork, or do nasty css hacks to customize the layout of the dropdown.

**Comment by ConneXNL** [comment]
+1

**Comment by savaa** [comment]
@dangrossman can you explain your vision of this feature?

**Comment by mhenley-uk** [comment]
+1

**Comment by marcbc** [comment]
+1

**Comment by godfern** [comment]
How do i override the templated??
Currently im creating an option object in angularjs and setting it as a scope variable

example:

$scope.options = {
                    format: 'DD-MM-YYYY',
                    startDate: $scope.stmtStartDate,
                    endDate: $scope.stmtEndDate,
                    minDate: moment(summaryData.onBoardDate).format('DD-MM-YYYY'),
                    maxDate: moment().subtract(1, 'days').format('DD-MM-YYYY'),
                    template: ('<div class="daterangepicker dropdown-menu">'+
                                '<div class="calendar left"></div>' +
                                '<div class="calendar right"></div>' +
                                  '<div class="ranges">' +
                                    '<div class="range_inputs">' +
                                      '<div class="daterangepicker_start_input">' +
                                        '<label for="daterangepicker_start"></label>' +
                                        '<input class="input-mini" type="text" name="daterangepicker_start" value="" disabled="disabled" />' +
                                      '</div>' +
                                      '<div class="daterangepicker_end_input">' +
                                        '<label for="daterangepicker_end"></label>' +
                                        '<input class="input-mini" type="text" name="daterangepicker_end" value="" disabled="disabled" />' +
                                      '</div>' +
                                      '<button class="applyBtn" disabled="disabled"></button>&nbsp;' +
                                      '<button class="cancelBtn"></button>' +
                                    '</div>' +
                                  '</div>' +
                                '</div>')
                };


The template is not replaced with the overwritten template......correct me if im wrong in setting the option object
im using "angular-daterangepicker": "~0.1.12" version

**Comment by godfern** [comment]
('<div class="daterangepicker dropdown-menu">'+
                                '<div class="calendar left"></div>' +
                                '<div class="calendar right"></div>' +
                                  '<div class="ranges">' +
                                    '<div class="range_inputs">' +
                                      '<div class="daterangepicker_start_input">' +
                                        '<label for="daterangepicker_start"></label>' +
                                        '<input class="input-mini" type="text" name="daterangepicker_start" value="" disabled="disabled" />' +
                                      '</div>' +
                                      '<div class="daterangepicker_end_input">' +
                                        '<label for="daterangepicker_end"></label>' +
                                        '<input class="input-mini" type="text" name="daterangepicker_end" value="" disabled="disabled" />' +
                                      '</div>' +
                                      '<button class="applyBtn" disabled="disabled"></button>&nbsp;' +
                                      '<button class="cancelBtn"></button>' +
                                    '</div>' +
                                  '</div>' +
                                '</div>')

**Comment by dangrossman** [comment]
You're commenting on an open pull request. There is no `template` option in the current date range picker library. If you want to override the template, you can do so by editing the `daterangepicker.js` file.

**Comment by godfern** [comment]
The template code look the same way defined in the

 var DRPTemplate = '<div class="daterangepicker dropdown-menu">' +
-                '<div class="calendar left"></div>' +
-                '<div class="calendar right"></div>' +
-                '<div class="ranges">' +
-                  '<div class="range_inputs">' +
-                    '<div class="daterangepicker_start_input">' +
-                      '<label for="daterangepicker_start"></label>' +
-                      '<input class="input-mini" type="text" name="daterangepicker_start" value="" disabled="disabled" />' +
-                    '</div>' +
-                    '<div class="daterangepicker_end_input">' +
-                      '<label for="daterangepicker_end"></label>' +
-                      '<input class="input-mini" type="text" name="daterangepicker_end" value="" disabled="disabled" />' +
-                    '</div>' +
-                    '<button class="applyBtn" disabled="disabled"></button>&nbsp;' +
-                    '<button class="cancelBtn"></button>' +
-                  '</div>' +
-                '</div>' +
-              '</div>';

**Comment by godfern** [comment]
Cannot we pass a config option instead of change in the core daterangepicker.js file?

**Comment by savaa** [comment]
It was a bad idea to create this request

**Pull request closed without merging**
