### PR TITLE
Fix bug that breaks view when select date range within 24 hours

### PR DESCRIPTION
**Pull request by honmaaax**
Forgive me if my understanding is mistaken.

### CODE REVIEW

**Comment by dangrossman** [comment]
What is the bug? What are the steps for me to reproduce it?

**Comment by honmaaax** [comment]
@dangrossman 
I can see the bug when I do as follows.

1. Use `react-bootstrap-daterangepicker`
2. Set `timePicker={true}` and `timePicker24Hour={true}`
3. View daterangepicker component on Chrome
4. Set date range within 24 hours
5. Click a day after endDate on daterangepicker's calender
6. You can see the bug

It fixes by the changes of this pull request.

**Comment by dangrossman** [comment]
I don't know anything about `react-bootstrap-daterangepicker` but I wasn't able to reproduce it using those instructions at http://www.daterangepicker.com/#config

**Comment by honmaaax** [comment]
@dangrossman 
Sorry, I checked that it reproduces the bug at the site as you said.
I should investigate the cause of the bug, so I close this pull request.

**Comment by honmaaax** [comment]
@dangrossman 
https://jsfiddle.net/4nrjLL20/
Please check this code and do as follows.

1. Click the input on preview.
2. Click the date after "2016-06-21"
3. The view of all data is broken

**Pull request closed without merging**
