### PR TITLE
Issue #793 - Empty date

### PR DESCRIPTION
**Pull request by ehhc**

### CODE REVIEW

**Comment by dangrossman** [comment]
This is a hack that doesn't cover many combinations of settings. It will lead to bugs, confusion, and lots of new issue reports. It is not so easy to support having no date selected in this codebase.

**Comment by marceloudi** [comment]
@dangrossman can you explain "too many combinations" with an real example?

In my case (and other users too):
- 90% of inputs in a huge software _must_ have initial empty values, so I need to _rewrite_ code to achieve this?
- Some filter fields _can_ be filled at start because of server stored "User Preferences". Ex: "Last 30 days", but in other cases the user clear the value

So, my question is: _rewriting_ code using "autoUpdateInput + callback" is _better practice_ than provide an initial option?

**Comment by dangrossman** [comment]
Your question: Maybe not, but nobody has coded that setting, and it would require more code than this PR contained to work with all the other settings this library has. I can't give specific examples, sorry. Out at dinner, and  my old open source repos aren't first priority when I'm working either.

**Comment by marceloudi** [comment]
Ok Dan! I understand it. I am a open source collaborator at ubuntu, so we share almost the same situation.
So I've tested @ehhc solution to exhaustion, and did not found any breaks.

Maybe you can considerate this proposal as a good help to you efforts.

I sincelery understand you.

Regards.

**Pull request closed without merging**
