### PR TITLE
Bug fixing - wrong calculation of the calendar position

### PR DESCRIPTION
**Pull request by EduardTrayan**
function (this.elements.outerHeight () incorrectly calculates the calendar position and returns [object Object]

http://bugs.jquery.com/ticket/12491
http://bugs.jquery.com/ticket/12159

### CODE REVIEW

**Comment by longzheng** [comment]
This is now an issue with jQuery 2.0+

Using ```outerHeight()``` without a boolean will now return an object instead of a number.

It is required to have an explicit boolean ```outerHeight(true)``` to return a number.

**Comment by dangrossman** [comment]
http://api.jquery.com/outerheight/ makes no mention of this.

I just tested on a page with jQuery 2.1.3 and `outerHeight()` returned a number, not an object.

**Comment by longzheng** [comment]
Sorry my bad, this is a bug with jQuery UI 1.8.18 specifically https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js

For example https://www.drupal.org/node/1916750

**Comment by dangrossman** [comment]
Sounds like you need to not run 1.8.18 then. That's 2-3 major versions behind.

**Comment by longzheng** [comment]
Yep, my bad, ignore me :(

**Pull request closed without merging**
