### PR TITLE
Update moment.js and zone()

### PR DESCRIPTION
**Pull request by YidingW**
Update moment.js to the latest;
According to https://github.com/moment/moment/issues/1779, change zone()
to utcOffset()

### CODE REVIEW

**Comment by vnen** [comment]
+1

**Comment by alanhamlett** [comment]
:+1:  +1

**Comment by Rudolph-Miller** [comment]
+1 :smile:

**Comment by hiperjp** [comment]
+1!

**Comment by dangrossman** [comment]
Do you +1 things randomly?

**Comment by hiperjp** [comment]
I'm sorry Dan, searching for last version (I'd face this issue today)

**Pull request closed without merging**
