### PR TITLE
Adding rangesRows option

### PR DESCRIPTION
**Pull request by sezeresen**
daterangepicker

### CODE REVIEW

**Comment by sezeresen** [comment]
Option name can be `rangesPerColumn` also.

**Comment by peter-mouland** [comment]
`rangesPerColumn` sounds good, default to `1`.

but this code is a little lazy though. a new ul for each column? not close to being semantic.  better would be to set widths for the li's based on the number of columns

**Comment by dangrossman** [comment]
I am quite happy to review my PRs myself, peter.

**Comment by dangrossman** [comment]
I'm going to opt not to take and support this feature. There's been no demand for something like this before, and multi-column lists can be accomplished purely in a stylesheet without library changes.

**Pull request closed without merging**
