### PR TITLE
Added dateLimitMin option to restrict minimum date range.  #424

### PR DESCRIPTION
**Pull request by tidemann**
dateLimitMin: (object) The minumum span between the selected start and end dates. Can have any property you can add to a moment object (i.e. days, months)

### CODE REVIEW

**Comment by ramdog** [comment]
Hi @dangrossman - I noticed you closed an issue looking for this feature:
https://github.com/dangrossman/bootstrap-daterangepicker/issues/606#issuecomment-87392873

I have pulled in @tidemann's change from this PR and it works consistently to the existing `dateLimit` option for enforcing a max range.

**Comment by sadortun** [comment]
Hi,

I would recommend the following syntax :

```
<input type="text" name="daterange" value="06/01/2015 - 06/07/2015" />
 
<script type="text/javascript">
$(function() {
    $('input[name="daterange"]').daterangepicker({
        format: 'MM/DD/YYYY',
        minDate: '06/01/2015',
        maxDate: '06/30/2015',
        dateLimit: { min: { days: 6 }  , max : {days: 8 } } 
// or
        dateLimit: { [ days: 6  ,days: 8 ] } 
    });
});
</script>
````

**Comment by lucasklaassen** [comment]
@dangrossman any reason this can't be merged?

**Comment by dangrossman** [comment]
`this.dateLimit` gets referenced 11 times throughout the code, where this patch uses the new `this.dateLimitMin` just twice. What do you think the chances of that being bug-free are, versus there being up to 9 times the `dateLimitMin` isn't getting applied when someone will expect it to be if it's added to the list of options? Along with changing dozens of lines of code because some auto-formatter disagreed with someone else's auto-formatter, making it hard to review what actually changed, are the reason this was passed over. I don't have time to invest lots of time into reviewing and fixing partial patches that'll almost definitely create more bugs, so I pass on all but very straightforward or very thorough PRs. I also only review PRs a few times a year. It's a five year old widget that's downloaded thousands of times a week, so a couple people over the course of years interested in an option is probably below the threshold to be worth carrying around and maintaining that option forever. There's nothing wrong with adding options/features to your own copy without them being in the original branch too.

**Pull request closed without merging**
