### PR TITLE
Allow the picker to drop "up"

### PR DESCRIPTION
**Pull request by gkostov**
Added **drop** option (defaults to "down") to control whether the picker opens "down" as usual or "up" (above the picker's button)

### CODE REVIEW

**Comment by juggy** [comment]
@dangrossman Any plans on merging all those pull requests? Especially this one, it is pretty straightforward.

**Comment by kirilvit** [comment]
Yeah! I need it in my project!

**Comment by dangrossman** [comment]
The appearance and positioning aren't right. The picker still has an arrow at the top, which normally points to the element it's attached to, but now points to nothing. It also overlaps whatever it's attached to, covering it half with the UI's shadow.

**Comment by gkostov** [comment]
Totally my fault here - I had only fixed the BS2 CSS as that is what we use. BS3 is now fixed as well and I also added to the bottom of the examples.

Cheers

**Comment by dangrossman** [comment]
Thank you :)

**Pull request merged**
