### PR TITLE
add before show event

### PR DESCRIPTION
**Pull request by bobmajdakjr**
allows you to completely reconfig the widget right before showing if needed. our form is two fields, and i needed to be able to change settings of each when activated. an example resetting the maxDate prior:

InputStart.on('before.daterangepicker',function(e,picker){ picker.maxDate = moment(InputEnd.val(),picker.locale.format); });

### CODE REVIEW

**Comment by dangrossman** [comment]
Thank you for offering this PR, but I'm going to decline it. I don't think this is a common use case.

**Comment by bobmajdakjr** [comment]
its a 1 line feature that does nothing but add value. i recommend it, else i'll maintain my fork which may fragment users. i'll even write the 1 line of documentation for you.

**Comment by dangrossman** [comment]
I recommend binding to the click and focus event of your input, which triggers this very same event without requiring any new code or documentation for everyone else.

**Comment by bobmajdakjr** [comment]
my original attempt went that direction, but that seems to be an async race condition. sometimes it would appear to work, sometimes it would not. i wrote it off as my focus() sometimes going before your focus() and other times visa versa.

**Comment by dangrossman** [comment]
You can add a delay to your function to avoid that

**Comment by dangrossman** [comment]
You can do a couple things: call `show()` again on the picker to make sure your changes take effect before re-running the code, attach a new `.daterangepicker()` to the input with your new options and call `.show()` on that...

**Comment by bobmajdakjr** [comment]
I love how the solution to avoid one line of elegance is convolution. computers and libraries in general are suppose to make life easier. I appreciate your work up to this point, but I think to maintain my fork then for now.

**Comment by dangrossman** [comment]
Just trying to help, since you seemed hesitant to alter your own copy for some reason.

**Pull request closed without merging**
