### PR TITLE
Allow optional/empty date on initial load

### PR DESCRIPTION
**Pull request by ducqui**
$("input.datepicker").daterangepicker({emptyDate: true, singleDatePicker: true});

### CODE REVIEW

**Comment by dangrossman** [comment]
You don't need to create a new options for this, "input initially empty" is the name of one of the examples on the documentation site already: http://www.daterangepicker.com/#example5

**Comment by alexandrejobin** [comment]
I think we must separate the need to have a input with an empty value and the need to have the input by updated as soon as you click on a date.

It's true that if you use autoUpdateInput: false, you can have an empty input but i need to also auto update the input field when you click on a date.

How can i do that?

**Comment by dangrossman** [comment]
@alexandrejobin The code for that is right here: http://www.daterangepicker.com/#example5

**Comment by alexandrejobin** [comment]
I saw the example but i just thought that natively, the library should allow an empty input instead of manually do everything (update the value, format the value).

Since that we can't init the input with an empty value AND still get the autoUpdateInput, i come up with this solution to have a startDate and endDate controlled separatly.

```
function init()
{
    var startDate = $("#StartDate");
    var endDate = $("#EndDate");

    attachDatePicker(startDate, null, endDate.val());
    attachDatePicker(endDate, startDate.val(), null);

    startDate.on("change", function (e)
    {
        attachDatePicker(endDate, startDate.val(), null);
    });

    endDate.on("change", function (e)
    {
        attachDatePicker(startDate, null, endDate.val());
    });
}

function attachDatePicker($input, minDate, maxDate)
{
    $input.daterangepicker({
        singleDatePicker: true,
        autoUpdateInput: false,
        minDate: minDate,
        maxDate: maxDate
    }, function (start, end, label)
    {
        // update input
        this.element
            .val(start.format("YYYY-MM-DD"))
            .trigger("change");
    });
}
```

**Comment by ducqui** [comment]
@dangrossman I realize that example#5 has "input initially empty". That's not the bug.
The bug is that you click the datepicker, want to choose Today (default start date), and NOTHING!!!
Why? The startDate and the selectedDate are the same and it WILL NOT trigger the update.

My code change was to allow initial input empty but also to update the date to Today on user selection.

The workaround is to choose another date, then choose Today again. That will work with the existing code, but that is BAD UX.

**Comment by dangrossman** [comment]
@ducqui The example does not have that fault. Unlike the callback function, the `apply` event is triggered even if you select the already selected date range. The example code uses that event. Feel free to try it out at http://www.daterangepicker.com/#example5.

**Comment by toxpal** [comment]
I know it's an old topic, but I discovered your plugin just yesterday, and it's amazing. 

The only confusing thing is that additional JS code is needed to initialize picker with empty value. In all other plugins, empty values are initialized by default, and you write extra code only if you want to add something (not to remove something).

I also strongly believe there should be a simple option to initialize picker with empty value (or even better - empty value should be used by default if input field is like `<input type="text" name="whatever" value="">` to avoid need of extra JS code, but that's just my opinion, and developer probably knows a good reason why this feature is not available.

**Comment by shushenghong** [comment]
@dangrossman i think we need an extra option to keep init input with empty value, it's not the same meaning with autoUpdateInput, 
if user click to choose some thing, autoUpdateInput will auto update the ui

**Comment by shushenghong** [comment]
@toxpal totally agree with u

**Comment by shushenghong** [comment]
my suck solution
```
var oval = $picker.val();
$picker.daterangepicker(xxxx);
if(!oval) {
    $picker.val('');
}
```

**Comment by aledmb** [comment]
> you click the datepicker, want to choose Today (default start date), and NOTHING!!!
> Why? The startDate and the selectedDate are the same and it WILL NOT trigger the update.

yeah, that's my issue too.

**Comment by kunambi** [comment]
Sorry to necro this thread, but it's very strange that the PR wasn't allowed. 

The option described - which imho should be default - is very different from `autoUpdateInput: false`, which breaks `autoApply: true`.

**Pull request closed without merging**
