### PR TITLE
new behavior on range click

### PR DESCRIPTION
**Pull request by borodulin**
Thank you for the wonderful widget, but I am constantly confronted with the need to change behavior when clicking on the range. Could you add a property, so as not to close the calendar when you select a specified range?

### CODE REVIEW

**Comment by borodulin** [comment]
http://jsfiddle.net/borodulin/vsx4kn7k/4/

**Comment by dangrossman** [comment]
Why?

**Comment by borodulin** [comment]
Users often do not understand what is happening. They need to clearly see the period and be able to clarify it. In the current implementation, when the dialog is closed, they open it again to make sure what period selected.

**Comment by vperron** [comment]
We are facing the issue too and I agree with @borodulin that making this an option if better than the hack we have implemented here (when it closes, open it again :/ )

**Pull request closed without merging**
