### PR TITLE
Fix issue in linkedCalendars, where if the maxDate is this month, the...

### PR DESCRIPTION
**Pull request by TheDartCode**
… right calendar showed a month after the maxDate prop.

Solves #984

### CODE REVIEW

**Comment by maxailloud** [comment]
I would be interested by this fix.

I'm using through https://github.com/fragaria/angular-daterangepicker and with your fix I have an error.
Don't know why but I have false in maxDate sometimes, so error when using clone method.
Adding 'this.maxDate && ' to the condition make it work.

**Comment by TheDartCode** [comment]
@maxailloud  The wrapper library you mention sets maxDate to false if none is provided (check line coffee/angular-daterangepicker.coffee#L146).
Don't know if it is the right approach to set false to that field, but in order to cover the case I added the check, too.

Cheers!
Hope the PR is accepted :)

**Comment by floydpraveen** [comment]
was looking for this, +1  for this PR

**Comment by maxailloud** [comment]
Any news here?

**Comment by dangrossman** [comment]
This code created new issue #1098

**Pull request merged**
