### PR TITLE
[Feat](Options): Add inline option

### PR DESCRIPTION
**Pull request by TooHTooH**

### CODE REVIEW

**Comment by WebberTakken** [comment]
Looks good, please pull

**Comment by Liiva** [comment]
The background color is off when the inline picker is placed in an element with a non-white background; for example a bootstrap well.

**Comment by dangrossman** [comment]
Hey guys. Thanks for the PR. Just wanted to let you know I'm still here, and hope to have time this week to review all the outstanding pull requests and start merging things in.

**Comment by TooHTooH** [comment]
Hey @Liiva , I added the background color only when it's a tooltips but i can't reproduce the other issue that you tell me about the focus, can you tell me on which browser you are ? Or if you can send me a fiddle or anything ? Thx for your feedback

**Comment by Liiva** [comment]
@TooHTooH, I added a jsfiddle here: https://jsfiddle.net/rdvxaaqb/
The layout is a bit weird (not sure why) but when you click on the top input field and press tab the inline picker disappears.

**Comment by TooHTooH** [comment]
Oh ok, I think I get it, I'm going to patch it, I was setting up the daterangepicker on a `div` element instead of an `input`, I'm gonna check the Blur event ASAP 
Thx

**Comment by TooHTooH** [comment]
@Liiva , Ok I think that's better : https://jsfiddle.net/b1epcrxu/

**Comment by dangrossman** [comment]
It looks messed up because the daterangepicker.css stylesheet wasn't loading

It also doesn't work very well with options that affect layout...

https://jsfiddle.net/a9sp1qhk/1/

**Comment by gabrielalan** [comment]
No thoughts on this? I really need this option :(

**Comment by TheBetpet** [comment]
Any chance this could be checked and implemented? It looks so messy with the calendars overflowing onto the next row and it's a nightmare to try and override the css to make it work.

**Comment by HansSchouten** [comment]
In case someone still needs an inline daterangepicker, I made a solution that does not require to change the original code: https://jsfiddle.net/9m63neo2/

**Pull request closed without merging**
