### PR TITLE
Added option to show/hide date range inputs

### PR DESCRIPTION
**Pull request by geo242**
This is useful when you only want to support using pre-defined date ranges

### CODE REVIEW

**Comment by artknight** [comment]
This is a really good idea! Should be merged asap.

**Comment by artknight** [comment]
I still do not understand why this is such a problem to merge this! It does not effect anything else nor will it in the future. When users express desire for this option to be there, why are you being difficult?

**Comment by dangrossman** [comment]
All pull requests against v1 were closed when v2 was released, as it was a near-complete rewrite and nothing would merge.

Please drop the attitude.

**Comment by artknight** [comment]
Oh ok, i understand. Sorry about that. When was v2 released? I did a pull yesterday and I was on v1.3.2

**Comment by dangrossman** [comment]
Yesterday

**Comment by artknight** [comment]
you are the man!

**Comment by artknight** [comment]
i do like the fact that now it opens starting with two consecutive months, not the same month twice!

**Pull request closed without merging**
