### PR TITLE
If endDate is clicked => time = 23:59:59

### PR DESCRIPTION
**Pull request by antonellopasella**
When you select a date with timepicker, the time should be the end of the day, not the beginning

### CODE REVIEW

**Comment by dangrossman** [comment]
The time should be whatever the hour/minute/second dropdowns indicate.

**Comment by antonellopasella** [comment]
When you choose a startDate, the endDate is disabled and reset to 00:00:00.
When you click the endDate (day), the dropdowns are enabled, but still 00:00:00

So, if you choose 12/06 and then 14/06 the result is
2015-06-12 00:00:00 to 2015-06-14 00:00:00

IMHO this is wrong, isn't?

**Comment by dangrossman** [comment]
Why do you have the time picker enabled if you don't want the user to choose the time *they* want?

**Comment by antonellopasella** [comment]
IMHO if I click 20/11/2015 I want to select the whole day.
At the moment I just select 20/11/2015 00:00:00, in fact I selected the end
of 19/11/2015

I'm wrong?

2015-11-03 16:24 GMT+01:00 Dan Grossman <notifications@github.com>:

> Why do you have the time picker enabled if you don't want the user to
> choose the time *they* want?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dangrossman/bootstrap-daterangepicker/pull/864#issuecomment-153387349>
> .
>



-- 
Antonello Pasella http://www.pasella.it

**Comment by sitelifters** [comment]
I agree with antonellopasella on this one. If you want to give users the option to select hours, but not require it, then when they select the end date without selecting an hour, it should default to the end of the day.

**Comment by dangrossman** [comment]
If it's a scheduling app and you're choosing the time for a doctor's appointment, does changing their selection to 23:59:59 make sense there? What about the dropoff time for a car reservation? Your preference for a "default", of which there is currently no such thing, is just that, a preference.

**Comment by antonellopasella** [comment]
Agreed but, 00:00:00 is a default preference too 😀

Il giovedì 3 dicembre 2015, Dan Grossman <notifications@github.com> ha
scritto:

> If it's a scheduling app and you're choosing the time for a doctor's
> appointment, does changing their selection to 23:59:59 make sense there?
> What about the dropoff time for a car reservation? Your preference for a
> "default", of which there is currently no such thing, is just that, a
> preference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dangrossman/bootstrap-daterangepicker/pull/864#issuecomment-161793997>
> .
>


-- 
Antonello Pasella http://www.pasella.it

**Comment by dangrossman** [comment]
There's no code that sets the time to 00:00:00 when the time picker is enabled. There is no default.

**Pull request closed without merging**
