### PR TITLE
button small class added for bs3

### PR DESCRIPTION
**Pull request by emamut**
Hi there,
This is a suggestion for the small buttons on bootstrap 3

### CODE REVIEW

**Comment by karan** [comment]
Why is the default small. If I want large button, adding the BS3 `btn-lg` class does not work now.

**Comment by dangrossman** [comment]
It's always been small, because there was only room for small buttons.

**Comment by karan** [comment]
Maybe add the ability to override this?

So I have done this:
- `display: none` on cancel button
- larger apply button with css

There could be a much better way to do this. Maybe have a `size` option, and a `visible` option for the two buttons.

**Comment by emamut** [comment]
Sounds like a great way to improve this plugin

**Comment by dangrossman** [comment]
You can override it through your stylesheet (write a more specific rule than Bootstrap's to target the buttons only in the picker), or by editing your local copy. Not everything needs to be an option.

**Comment by karan** [comment]
Having options make it more easily configurable and user friendly though.

**Comment by dangrossman** [comment]
What classes get applied to the buttons is already an option. There doesn't need to be another "size" option that does the same thing.

**Pull request merged**
